const chatData: { [key: string]: string } = {
  "hi": "Hi there! How can I assist you with AI-Solution today?",
  "hello": "Hi there! How can I assist you with AI-Solution today?",
  "what is ai-solution?": "AI-Solution is a cutting-edge platform designed to provide AI-powered solutions for businesses and individuals.",
  "features of ai-solution": "AI-Solution offers features like data analysis, predictive modeling, chatbot integration, and AI-powered insights tailored to your needs.",
  "how can ai-solution help me?": "AI-Solution can streamline your business operations, provide valuable insights, and automate repetitive tasks to save time and resources.",
  "pricing of ai-solution": "Our pricing depends on the plan you choose. Please visit the pricing section of our website or contact us for detailed information.",
  "support options": "We offer 24/7 customer support via email, chat, and phone to assist you with any issues or questions.",
  "integrations available": "AI-Solution integrates seamlessly with popular platforms like Google Workspace, Microsoft Office, and many CRM tools.",
  "use cases": "AI-Solution is ideal for e-commerce, healthcare, finance, education, and many other industries seeking AI-driven improvements.",
  "data privacy": "We prioritize your data privacy and comply with all major regulations, including GDPR and CCPA.",
  "how to get started?": "To get started, sign up on our website and choose the plan that best suits your needs. Our onboarding process is quick and easy!",
  "customization options": "AI-Solution offers extensive customization to tailor the platform to your unique requirements.",
  "contact information": "You can reach us at support@ai-solution.com or call us at +123-456-7890 for further assistance.",
  "bye": "Goodbye! Feel free to return if you have more questions about AI-Solution.",
  "thank you": "You're welcome! Let me know if there's anything else I can help with.",
  "help": "I'm here to answer your questions about AI-Solution. What would you like to know?",
  "tell me more about ai-solution": "AI-Solution combines advanced AI technologies to help you achieve your goals efficiently and effectively.",
  "what can you do?": "I can assist with information about AI-Solution, answer your questions, and guide you through its features.",
  "who made you?": "I was developed as part of the AI-Solution platform to assist users like you.",
  "what's your name?": "I'm the AI-Solution Chatbot, your virtual assistant!",
  "how are you?": "I'm just a bot, but I'm here to help you!",
  "where are you located?": "I live in the digital world, right here in the AI-Solution system.",
  "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
  "do you like ai-solution?": "Of course! AI-Solution is an amazing platform that helps people achieve their goals with AI.",
  "who are your creators?": "AI-Solution was developed by a talented team of engineers and AI specialists.",
  "can i try ai-solution for free?": "Yes, we offer a free trial. Please visit our website to learn more and get started.",
  "what industries does ai-solution support?": "AI-Solution supports various industries like healthcare, finance, education, and more.",
  "what makes ai-solution unique?": "Our platform is designed to be user-friendly, highly customizable, and packed with cutting-edge AI features.",
  "can you help me decide a plan?": "Absolutely! Let me know your requirements, and I’ll guide you to the best plan for your needs.",
  "is ai-solution secure?": "Yes, we follow stringent security protocols and comply with major data privacy regulations.",
  "goodbye": "Goodbye! Take care and come back anytime for assistance.",
  "Who are you?":"I am the Ai-Solution Chatbpt, your virtual assistant!",
};

export default chatData;
